name: Use Reusable Workflow
on:
  push:
    branches:
      - master
jobs:
  ci:
    uses: ./.github/workflows/reusable.yml
    with:
      input-name: Gilbert Subay
    secrets:
      some-secret: ${{ secrets.PERUSAHAAN_SAYA }}
  print-deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy output
        run: echo "${{ needs.ci.outputs.result }}"
